# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TehStoneMan/GreenScreen/issues"

[[mods]]
# The modid of the mod
modId="grnscrn"

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory

 # A display name for the mod
displayName="GreenScreen"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="http://tehstoneman.github.io/greenscreen.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://minecraft.curseforge.com/projects/greenscreen"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="GreenScreenLogo.png"

# A text field displayed in the mod UI
authors="TehStoneMan"

# The description text for the mod (multi line!) (#mandatory)
description='''Add a Greenscreen to Minecraft for video composition'''