modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TehStoneMan/GreenScreen/issues"
[[mods]]
modId="grnscrn"
version="${file.jarVersion}"
displayName="GreenScreen"
updateJSONURL="http://tehstoneman.github.io/greenscreen.json"
displayURL="http://minecraft.curseforge.com/projects/greenscreen"
logoFile="GreenScreenLogo.png"
authors="TehStoneMan"
description='''Add a Greenscreen to Minecraft for video composition'''